id: PB0CB59F1
initial_creation_type: input
source_metadata:
  title: Songs and Poems Series
  language: es
  description: 'A selection of spiritual songs (mgur; glu) or poems:'
  volume:
    a19c7d28360a4f2d84faa515648fc4c6:
      title: Acrostic Song
      parent: Acrostic
    2202730851534768925ec60f70a57329:
      title: A Song for Travelling from Sikkim to Tibet
      parent: Advice
    548a0659091c45ae812040fc2332ed0a:
      title: Advice to Myself Exposing Hidden Flaws
      parent: Advice
    4afb747d16984289b0d9898ac9efaa96:
      title: Khandro's Plea
      parent: Advice
    4b56f9667783409ebe20754dc106aeb8:
      title: 'The Blissful Path to Awakening: A Song on the Essence of Definitive
        Meaning'
      parent: Advice
    e6499a2f81944727a6923b85ebd05e93:
      title: How to Take the Practice to Heart
      parent: Advice
    cef65d66fa1449edb1ff8a26209ae413:
      title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
      parent: Advice
    f238bfe98b664317b6de0be84baf8a36:
      title: Many Are the Scholars Who Travel Empty-Handed to the Realm of the Dead
      parent: Advice
    68260888518847ebbfee483d0b04b9b9:
      title: 'Divine Music: Words of Encouragement for the Authentic Path'
      parent: Advice
    a6cdfb153ca1456795ca4956a899ad5f:
      title: Song of the Enchanting Wildwoods
      parent: Advice
    e4b4737e13124558b5b418aa2783391a:
      title: A Song of Amazement Inspired by Practice Experience
      parent: Advice
    a5cd4ee9f8f9455f81f783c78a77a0c6:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      parent: Advice
    2657514f4d994598b9e5600a15a4f5f1:
      title: Types of Spiritual Song
      parent: Classification
    5e5b847f116046f287e2c6cc23c364fe:
      title: On Jetsün Drakpa Gyaltsen’s How to Take the Practice to Heart
      parent: Commentaries
    e4430a45d11f4e38a3fcc162c6a69d1c:
      title: A Song to Aid the Recollection of Parental Kindness and Encourage the
        Recitation of the Maṇi Mantra
      parent: Compassion
    a19c7a28c62d4bfcb8b7ac3a5290d622:
      title: A Song of Compassion
      parent: Compassion
    ac3e8e05ae1c4ef1a9f95b8e3b94eaec:
      title: When Remembering My Mother
      parent: Compassion
    0deb4db728bb4172acf68fa23a9b0726:
      title: A Lamenting Plea for Compassion
      parent: Devotion
    be582d1636ae4377a1427ac71d06cdb4:
      title: A Song Recalling the Noble Guru’s Kindness
      parent: Devotion
    c7d225a68e6c4f20bac522dae9614ff5:
      title: A Song Requested by the Buddhist Monk Jamyang Yönten Gyatso
      parent: Devotion
    db219c0ed17f4d40b96dd0aa48e60589:
      title: Lament Composed in a State of Deep Sadness
      parent: Devotion
    3c00989858f046a3b453f559f69bdac7:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      parent: Devotion
    d41ff1409065439da89e4cead9cfdea3:
      title: 'Piercing Devotion: A Lament for Lama Sakyapa'
      parent: Devotion
    b95d46a7d84c4e5e885f36f889a66a17:
      title: 'Tremendous Piercing of the Heart: A Lament Recalling the Guru'
      parent: Devotion
    2fed2d3ec67b4b2a9fb570ba24140f74:
      title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great
        Guru of Oḍḍiyāna'
      parent: Devotion
    f941d0ce1998488ebb4567151ccbae74:
      title: The Song of the Vajra
      parent: Dzogchen
    54ad0755cc9a40ba86dcf0f076382fdc:
      title: A Song in Six Verses
      parent: Dzogchen
    241fff30d9cc4dc5a3d2e14172358398:
      title: Song of Experiential Certainty
      parent: Dzogchen
    e99587da5339410aacc069bf89099b1f:
      title: Song that Arose Spontaneously at Taktse Podrang, Sikkim
      parent: Dzogchen
    0d38b130969d42449d5e1982464fbf05:
      title: Spontaneously Written Song of Experience
      parent: Dzogchen
    b6b5354481bb4a68bb43ad0b0efc2aad:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    30a89f1c6aef482e8ca6e30d7db94dd6:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    a4f0c2f0ca9e41f1a6295bea2dc7c8bf:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    e537be5a19184edba4ece24127bc0589:
      title: In This Pure Awareness
      parent: Dzogchen
    9530f8c5c45f43b486375feab348c25a:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Dzogchen
    08769ff264eb43f19301e30ef5bd861a:
      title: Five-Verse Doha of Yogic Realization
      parent: Dzogchen
    4b39ae8df73a467cb8bddec0e668952f:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Dzogchen
    54399f69e5b847d2b1cf71c7afd74545:
      title: Natural Great Peace
      parent: Dzogchen
    cc6946ef35784fc2b2bc6fc00b479a56:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Feast Songs
    8ea0f280654a4e11973afac58f033ca8:
      title: Song of the Feast (Tsok Lu)
      parent: Feast Songs
    b251990198f942a5b03e31c274f0913a:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: General
    71ed74f4e81e4e2da632fcc9225ff798:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: General
    c38ab6e2870e4e50ace0823b7003a99e:
      title: A Short Song of Practice
      parent: General
    15614d8bf4d9491eb6a05a55271a2bf3:
      title: When Flowers Were Ravaged by the Frost
      parent: Impermanence
    4fe5878523db4941bde605a4d53dcb90:
      title: Verses of Advice for Meditating on Impermanence
      parent: Impermanence
    6ea6e69c0ad04625ab4d3fe58161c09b:
      title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
        and Fulfilment'
      parent: Joy
    41882105a68b4000a50b71cbecaf3fc1:
      title: Drawing Out the Quintessence of the View
      parent: Lamdré
    6edf308d2f4147eea5b8437506f70c74:
      title: Song of Deathlessness
      parent: Longevity
    07e3dde6aa1d4b8684f0ea5b7371dc6a:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Mahāmudrā
    00b187a34dc3409c97b908ae97f441a8:
      title: 'Lightning Band of Faith: A Song to Invoke the Master’s Wisdom Mind'
      parent: Prayer
    f28b8be93e85440995e4f9f0888828b9:
      title: A Song of Prayer to Jamyang Loter Wangpo
      parent: Prayer
    a66546249f5643f094b4da5dd86eb970:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Sacred Places
    c4a4e613a9a8471eabc9d5f9921f91bf:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    c09dd49cb3cb4b428957ead959797488:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    ce9cbf6c96c640c6ad6915877af4e768:
      title: 'Great Stake to the Heart: A Song of Sadness'
      parent: Sadness
    485db4432b0d46ee9024714506076f4d:
      title: Song of Prayer to Milarepa
      parent: Sadness
    a8baf72eedf641ef87c39f9e6df61000:
      title: Twelve and a Half Crippled Verses
      parent: Wonder
created_at: '2022-03-01T05:55:44.198821'
last_modified_at: '2022-03-01T05:55:44.198824'
